In [7]:
# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

# Import Path from pathlib
from pathlib import Path

# Import yfinance package
import yfinance as yf

# Import pandas package
import pandas as pd

In [ ]:
# Pull the data for the first security
stock_data_1 = yf.Ticker("NG=F")
stock_data_1.info

In [15]:
import datetime as dt
stock_data = stock_data_1.history(period="2y", interval="1d")

In [34]:
stock_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-01-23 00:00:00-05:00,3.450,3.564,3.243,3.447,130377,0.0,0.0
2023-01-24 00:00:00-05:00,3.450,3.595,3.224,3.258,62585,0.0,0.0
2023-01-25 00:00:00-05:00,3.242,3.251,2.992,3.067,40750,0.0,0.0
2023-01-26 00:00:00-05:00,3.003,3.003,2.761,2.944,47669,0.0,0.0
2023-01-27 00:00:00-05:00,2.876,3.176,2.832,3.109,128689,0.0,0.0
...,...,...,...,...,...,...,...
2025-01-10 00:00:00-05:00,3.709,4.018,3.685,3.989,229112,0.0,0.0
2025-01-13 00:00:00-05:00,4.347,4.369,3.845,3.934,195514,0.0,0.0
2025-01-14 00:00:00-05:00,3.930,4.059,3.736,3.968,167416,0.0,0.0
2025-01-15 00:00:00-05:00,3.955,4.141,3.859,4.083,167416,0.0,0.0
2025-01-21 00:00:00-05:00,3.815,3.914,3.719,3.769,186875,0.0,0.0

In [37]:
stock_data_shift_date = (
            stock_data.index[-1] - pd.DateOffset(days=30)
        )
stock_data_shift_date

Timestamp('2024-12-22 00:00:00-0500', tz='America/New_York')

In [38]:
prediction_data = stock_data[stock_data.index <= stock_data_shift_date]
prediction_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2023-01-23 00:00:00-05:00,3.450,3.564,3.243,3.447,130377,0.0,0.0
2023-01-24 00:00:00-05:00,3.450,3.595,3.224,3.258,62585,0.0,0.0
2023-01-25 00:00:00-05:00,3.242,3.251,2.992,3.067,40750,0.0,0.0
2023-01-26 00:00:00-05:00,3.003,3.003,2.761,2.944,47669,0.0,0.0
2023-01-27 00:00:00-05:00,2.876,3.176,2.832,3.109,128689,0.0,0.0
...,...,...,...,...,...,...,...
2024-12-16 00:00:00-05:00,3.210,3.253,3.145,3.214,172230,0.0,0.0
2024-12-17 00:00:00-05:00,3.227,3.394,3.091,3.308,229155,0.0,0.0
2024-12-18 00:00:00-05:00,3.368,3.441,3.312,3.374,193391,0.0,0.0
2024-12-19 00:00:00-05:00,3.405,3.646,3.391,3.584,195546,0.0,0.0
2024-12-20 00:00:00-05:00,3.632,3.828,3.554,3.748,221930,0.0,0.0

In [39]:
original_data = stock_data[stock_data.index > stock_data_shift_date]
original_data

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-12-23 00:00:00-05:00,3.869,3.944,3.581,3.656,125622,0.0,0.0
2024-12-24 00:00:00-05:00,3.695,3.958,3.666,3.946,66852,0.0,0.0
2024-12-26 00:00:00-05:00,3.970,4.010,3.652,3.715,67209,0.0,0.0
2024-12-27 00:00:00-05:00,3.707,3.887,3.370,3.514,189959,0.0,0.0
2024-12-30 00:00:00-05:00,3.657,4.201,3.648,3.936,374324,0.0,0.0
2024-12-31 00:00:00-05:00,3.915,4.012,3.577,3.633,184552,0.0,0.0
2025-01-02 00:00:00-05:00,3.656,3.801,3.541,3.660,156670,0.0,0.0
2025-01-03 00:00:00-05:00,3.669,3.680,3.330,3.354,188094,0.0,0.0
2025-01-06 00:00:00-05:00,3.554,3.726,3.502,3.672,228124,0.0,0.0
2025-01-07 00:00:00-05:00,3.705,3.738,3.427,3.449,182148,0.0,0.0
2025-01-08 00:00:00-05:00,3.448,3.694,3.427,3.651,189259,0.0,0.0
2025-01-09 00:00:00-05:00,3.682,3.830,3.552,3.701,145203,0.0,0.0
2025-01-10 00:00:00-05:00,3.709,4.018,3.685,3.989,229112,0.0,0.0
2025-01-13 00:00:00-05:00,4.347,4.369,3.845,3.934,195514,0.0,0.0
2025-01-14 00:00:00-05:00,3.930,4.059,3.736,3.968,167416,0.0,0.0
2025-01-15 00:00:00-05:00,3.955,4.141,3.859,4.083,167416,0.0,0.0
2025-01-21 00:00:00-05:00,3.815,3.914,3.719,3.769,186875,0.0,0.0